"""added Os and browser field to session

Revision ID: 28922c9b2292
Revises: 260c75511af8
Create Date: 2026-04-10 22:44:57.989752

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '28922c9b2292'
down_revision: Union[str, Sequence[str], None] = '260c75511af8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('session', sa.Column('os', sa.String(), nullable=True))
    op.add_column('session', sa.Column('browser', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('session', 'browser')
    op.drop_column('session', 'os')
    # ### end Alembic commands ###
